routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/series', 'SeriesController@index')->name('listar_series');
Route::get('/series/criar', 'SeriesController@create')->name('criar_series_pagina')
    ->middleware('autenticador');
Route::post('/series/criar', 'SeriesController@store')->name('criar_series')
    ->middleware('autenticador');
Route::delete('/series/{id}', 'SeriesController@destroy')->name('remover_series')
    ->middleware('autenticador');
Route::post('/series/{id}/editaNome', 'SeriesController@editaNome')
    ->middleware('autenticador');
Route::get('/series/{id}/temporadas', 'TemporadasController@index');
Route::get('/temporadas/{temporada}/episodios', 'EpisodiosController@index');
Route::post('/temporadas/{temporada}/episodios/assistir', 'EpisodiosController@assistir')
    ->middleware('autenticador');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/entrar', 'EntrarController@index')->name('login');
Route::post('/entrar', 'EntrarController@entrar');
Route::get('/registrar', 'RegistroController@create');
Route::post('/registrar', 'RegistroController@store');
Route::get('/sair', function () {
    \Illuminate\Support\Facades\Auth::logout();
    return redirect('/entrar');
});

app/Serie.php
<?php


namespace App;


use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Storage;

class Serie extends Model
{
    public $timestamps = false;
    protected $fillable = ['nome', 'capa'];

    public function temporadas()
    {
        return $this->hasMany(Temporada::class);
    }

    public function getUrlImagemAttribute()
    {
        if (is_null($this->capa)) {
            return Storage::url('series/sem-imagem.png');
        }
        return Storage::url($this->capa);
    }
}

app/Http/Controllers/SeriesController.php
<?php

namespace App\Http\Controllers;


use App\Events\NovaSerie as NovaSerieEvent;
use App\Http\Requests\SeriesRequest;
use App\Mail\NovaSerie;
use App\Serie;
use App\Services\CriadorSerie;
use App\Services\RemovedorSerie;
use App\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Mail;

class SeriesController extends Controller
{
    public function index(Request $request)
    {
        $series = Serie::query()
            ->orderBy('nome')
            ->get();

        $mensagem = $request->session()->get('mensagem');

        return view('series.index', compact('series', 'mensagem'));
    }

    public function create()
    {
        return view('series.create');
    }

    public function store(SeriesRequest $request, CriadorSerie $criadorSerie)
    {
        $capa = null;

        if ($request->hasFile('capa')) {
            $capa = $request->file('capa')->store('series');
        }

        $serie = $criadorSerie->criarSerie($request->nome, $request->qtd_temporadas, $request->qtd_episodios, $capa);
        $eventoNovaSerie = new NovaSerieEvent($request->nome, $request->qtd_temporadas, $request->qtd_episodios);
        event($eventoNovaSerie);

        $request
            ->session()
            ->flash('mensagem', "Série {$serie->nome} e seus respectivos episódios e temporadas criados");

        return redirect()->route('listar_series');
    }

    /*
     * Uma série pode ser removida em cascata adicionando o método onDelete('cascate') na migration,
     * Na parte de referência da foreign key
     * Obs: Testar se cascadeOnDelete() funciona
     * */
    public function destroy(Request $request, RemovedorSerie $removedorSerie)
    {
        $nomeSerie = $removedorSerie->removerSerie($request->id);

        $request
            ->session()
            ->flash('mensagem', "Série $nomeSerie removida com sucesso");
        return redirect()->route('listar_series');
    }

    public function editaNome(int $id, Request $request)
    {
        $serie = Serie::find($id);
        $serie->nome = $request->nome;
        $serie->save();
    }
}

resources/views/series/create.blade.php
@extends('layout')

@section('cabecalho')
    Adicionar Série
@endsection

@section('conteudo')
    @include('erros', ['errors' => $errors])

    <form method="post" enctype="multipart/form-data">
        @csrf
        <div class="row">
            <div class="col col-8">
                <label for="nome">Nome</label>
                <input class="form-control" type="text" name="nome" id="nome">
            </div>

            <div class="col col-2">
                <label for="qtd_temporadas">Qtd. Temporadas</label>
                <input class="form-control" type="number" name="qtd_temporadas" id="qtd_temporadas">
            </div>

            <div class="col col-2">
                <label for="qtd_episodios">Qtd. Episódios</label>
                <input class="form-control" type="number" name="qtd_episodios" id="qtd_episodios">
            </div>
        </div>

        <div class="row">
            <label for="capa">Capa</label>
            <input class="form-control" type="file" name="capa" id="capa">
        </div>

        <button class="btn btn-primary mt-3">Adicionar</button>
    </form>
@endsection

resources/views/series/index.blade.php
@extends('layout')

@section('cabecalho')
    Séries
@endsection

@section('conteudo')
    @include('mensagem', ['mensagem' => $mensagem])

    @auth
        <a href="{{ route('criar_series_pagina') }}" class="btn btn-dark mb-2">Adicionar</a>
    @endauth

    <ul class="list-group">
        @foreach($series as $serie)
            <li class="list-group-item d-flex justify-content-between align-items-center">
                <div>
                    <a href="{{ $serie->url_imagem }}">
                        <img src="{{ $serie->url_imagem }}" class="img-thumbnail" height="100px" width="100px">
                    </a>
                    <span class="ml-3" id="nome-serie-{{ $serie->id }}">{{ $serie->nome }}</span>
                </div>

                <div class="input-group w-50" hidden id="input-nome-serie-{{ $serie->id }}">
                    <input type="text" class="form-control" value="{{ $serie->nome }}">
                    <div class="input-group-append">
                        <button class="btn btn-primary" onclick="editarSerie({{ $serie->id }})">
                            <i class="fas fa-check"></i>
                        </button>
                        @csrf
                    </div>
                </div>

                <span class="d-flex">
                    @auth
                        <button class="btn btn-info btn-sm mr-1" onclick="toggleInput({{ $serie->id }})">
                        <i class="fas fa-edit"></i>
                    </button>
                    @endauth

                    <a href="/series/{{ $serie->id }}/temporadas" class="btn btn-info btn-sm mr-1">
                        <i class="fas fa-external-link-alt"></i>
                    </a>

                        @auth
                        <form method="post" action="/series/{{ $serie->id }}"
                              onsubmit="return confirm('Tem certeza que deseja remover {{ addslashes($serie->nome) }}?')">
                        @csrf
                            @method('DELETE')
                        <button class="btn btn-danger btn-sm">
                            <i class="far fa-trash-alt"></i>
                        </button>
                    </form>
                    @endauth
                </span>

            </li>
        @endforeach
    </ul>

    <script>
        function toggleInput(serieId) {
            const nomeSerieEl = document.getElementById(`nome-serie-${serieId}`);
            const inputSerieEl = document.getElementById(`input-nome-serie-${serieId}`);
            if (nomeSerieEl.hasAttribute('hidden')) {
                nomeSerieEl.removeAttribute('hidden');
                inputSerieEl.hidden = true;
            } else {
                inputSerieEl.removeAttribute('hidden');
                nomeSerieEl.hidden = true;
            }
        }

        function editarSerie(serieId) {
            let formData = new FormData();
            const nome = document
                .querySelector(`#input-nome-serie-${serieId} > input`)
                .value;
            const token = document
                .querySelector(`input[name="_token"]`)
                .value;
            formData.append('nome', nome);
            formData.append('_token', token);
            const url = `/series/${serieId}/editaNome`;
            fetch(url, {
                method: 'POST',
                body: formData
            }).then(() => {
                toggleInput(serieId);
                document.getElementById(`nome-serie-${serieId}`).textContent = nome;
            });
        }
    </script>
@endsection